CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_salt BLOB,password_hash BLOB,created_at INTEGER NOT NULL);
INSERT INTO users(id,username,created_at) VALUES('admin','admin',0);
ALTER TABLE devices ADD COLUMN owner_id TEXT REFERENCES users(id);
UPDATE devices SET owner_id='admin';
CREATE TRIGGER devices_owner_insert BEFORE INSERT ON devices WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
CREATE TRIGGER devices_owner_update BEFORE UPDATE OF owner_id ON devices WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
ALTER TABLE pairings ADD COLUMN owner_id TEXT REFERENCES users(id);
UPDATE pairings SET owner_id='admin';
CREATE TRIGGER pairings_owner_insert BEFORE INSERT ON pairings WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
CREATE TRIGGER pairings_owner_update BEFORE UPDATE OF owner_id ON pairings WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
ALTER TABLE rooms ADD COLUMN owner_id TEXT REFERENCES users(id);
UPDATE rooms SET owner_id='admin';
CREATE TRIGGER rooms_owner_insert BEFORE INSERT ON rooms WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
CREATE TRIGGER rooms_owner_update BEFORE UPDATE OF owner_id ON rooms WHEN NEW.owner_id IS NULL BEGIN SELECT RAISE(ABORT,'owner required'); END;
CREATE INDEX devices_owner ON devices(owner_id);
CREATE TABLE room_users(room_id TEXT NOT NULL REFERENCES rooms(id),user_id TEXT NOT NULL REFERENCES users(id),since_message_id INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(room_id,user_id));
CREATE TABLE invitations(id TEXT PRIMARY KEY,code_hash TEXT NOT NULL UNIQUE,kind TEXT NOT NULL CHECK(kind IN ('registration','room')),room_id TEXT REFERENCES rooms(id),created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,used_at INTEGER,used_by TEXT REFERENCES users(id),revoked_at INTEGER);
CREATE INDEX invitations_creator ON invitations(created_by,created_at);
ALTER TABLE messages ADD COLUMN sender_name TEXT NOT NULL DEFAULT 'admin';
