// Disposable loopback environment with a synthetic microphone; never production.
const fs=require('fs'),assert=require('assert/strict');const path=require('path');const library=process.env.POCKETLINK_PLAYWRIGHT||'playwright';const {chromium}=require(library);const {ws:WS}=require(path.join(path.dirname(require.resolve(library)),'../playwright-core/lib/utilsBundle.js'));
const origin=process.env.POCKETLINK_TEST_ORIGIN||'https://127.0.0.1:3443';assert.equal(new URL(origin).hostname,'127.0.0.1');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});let peer;try{const c=await browser.newContext({ignoreHTTPSErrors:true,permissions:['microphone'],viewport:{width:1440,height:1000}}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.click('#mode-admin');await p.fill('#password',fs.readFileSync(process.env.POCKETLINK_TEST_PASSWORD_FILE,'utf8').trim());await p.click('#login-form button');await p.waitForSelector('#workspace:not([hidden])');
const api=async(path,data,method='POST')=>{const response=await c.request.fetch(origin+'/api/v1/'+path,{method,headers:path.startsWith('device/')?{}:{Origin:origin},data});assert(response.ok(),await response.text());return response.json()};
const pair=await api('pairings',{name:'语音测试设备'});const device=await api('device/pair',{code:pair.code,sn:'voice-'+Date.now()});
const room=await api('rooms',{name:'对讲验证'});await api('rooms/'+room.id+'/members/'+device.device.id,undefined,'PUT');
const packets=[];let binary=0;peer=new WS(origin.replace('https','wss')+'/api/v1/device/voice/'+room.id,'pocketlink.voice.v1',{rejectUnauthorized:false,headers:{Authorization:'Bearer '+device.credential}});peer.on('message',(data,isBinary)=>{if(isBinary)binary++;else packets.push(JSON.parse(data))});await new Promise((resolve,reject)=>{peer.once('open',resolve);peer.once('error',reject)});
await p.click('#refresh');await p.click('#nav-rooms');await p.click('#room-picker');await p.getByRole('option',{name:'对讲验证',exact:true}).last().click();await p.waitForSelector('#room-detail:not([hidden])');await p.click('#voice-connect');await p.waitForFunction(()=>!document.getElementById('voice-talk').disabled);assert.equal(binary,0);await p.focus('#voice-talk');await p.keyboard.down(' ');await p.waitForSelector('#voice-talk[data-speaking=true]');await p.waitForTimeout(600);await p.keyboard.up(' ');assert(binary>3,'microphone PCM not forwarded');const stopped=binary;await p.waitForTimeout(300);assert(binary<=stopped+2,'PCM continued after release');
peer.send(JSON.stringify({type:'request',request_id:99}));await p.waitForTimeout(100);const grant=packets.find(v=>v.type==='grant'&&v.request_id===99);assert(grant);const frame=Buffer.alloc(648);frame.writeUInt32BE(grant.stream,0);frame.writeUInt32BE(1,4);peer.send(frame);await p.waitForFunction(()=>document.getElementById('voice-status').textContent.includes('语音测试设备'));
await p.focus('#voice-talk');await p.keyboard.down(' ');await p.waitForFunction(()=>document.getElementById('voice-status').textContent.includes('有人正在讲话'));await p.keyboard.up(' ');peer.send(JSON.stringify({type:'release',stream:grant.stream}));
await p.click('#nav-overview');assert(await p.locator('#voice-talk').isDisabled());await p.click('#nav-rooms');assert.equal(await p.textContent('#voice-connect'),'连接对讲');assert.deepEqual(errors,[]);console.log('Browser microphone PCM to device, device to browser, contention, release and navigation cleanup: PASS');await c.close();}finally{peer?.close();await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
